"""Add SysSupplierReq audit table for AI supplier selection

Revision ID: 39fdf94586c9
Revises: 4318ac15cbca
Create Date: 2025-11-15 19:41:46.913774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39fdf94586c9'
down_revision = '4318ac15cbca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # EDITED: Removed all ALTER TABLE commands - only creating new sys_supplier_req table
    op.create_table('sys_supplier_req',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('request', sa.String(length=2000), nullable=True),
    sa.Column('chosen_supplier_id', sa.Integer(), nullable=True),
    sa.Column('chosen_unit_price', sa.DECIMAL(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chosen_supplier_id'], ['supplier.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # EDITED: Simplified - just drop the sys_supplier_req table
    op.drop_table('sys_supplier_req')
    op.alter_column('item', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.add_column('customer', sa.Column('email_opt_out', sa.BOOLEAN(), nullable=True))
    op.add_column('customer', sa.Column('email', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'customer', type_='unique')
    op.alter_column('customer', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_table('sys_supplier_req')
    # ### end Alembic commands ###
