"""add_syssupplierreq_audit_table

Revision ID: 4318ac15cbca
Revises: 6a695f4b1a5f
Create Date: 2025-11-15 09:27:08.716268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4318ac15cbca'
down_revision = '6a695f4b1a5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - MANUALLY EDITED to remove unwanted changes ###
    op.create_table('sys_supplier_req',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('chosen_supplier_id', sa.Integer(), nullable=True),
    sa.Column('chosen_unit_price', sa.DECIMAL(), nullable=True),
    sa.Column('request', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['chosen_supplier_id'], ['supplier.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - MANUALLY EDITED to remove unwanted changes ###
    op.drop_table('sys_supplier_req')
    # ### end Alembic commands ###
