"""Add SysSupplierReq table for AI audit

Revision ID: 6a695f4b1a5f
Revises: ce0ed7ff7a08
Create Date: 2025-11-15 08:59:08.079453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a695f4b1a5f'
down_revision = 'ce0ed7ff7a08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - EDITED to only create sys_supplier_req ###
    op.create_table('sys_supplier_req',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('chosen_supplier_id', sa.Integer(), nullable=True),
    sa.Column('chosen_unit_price', sa.DECIMAL(), nullable=True),
    sa.Column('request', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['chosen_supplier_id'], ['supplier.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - EDITED to only drop sys_supplier_req ###
    op.drop_table('sys_supplier_req')
    # ### end Alembic commands ###
